### ISSUE TITLE
Spash sounds are misplaced

### ISSUE THREAD

**Issue by Adnan1091** [t-affeldt/climate#1] opened 2020-07-20 06:17 UTC
[ScreenRecord-20200717-093925.zip](https://github.com/t-affeldt/climate/files/4945823/ScreenRecord-20200717-093925.zip)

**Comment by t-affeldt** [comment] 2020-08-19 12:08
Hello. Thank you for your report!

I tried my best and I cannot reproduce your issue. The sounds are played when stepping into a puddle and when stepping out of one, so they might be slightly offset. Despite trying to replicate the scenario, I didn't get such bad results as in your video.

Either way, I don't think there's much I can do with it. I don't mess with coordinates myself. I only register the sound as a footstep sound for puddles. So any related issues go back to the engine. I could maybe find a hacky workaround but it's working on both of my test machines.

I will have to close this issue now. But please feel free to reopen if you find any useful information that helps me replicate the issue.

**Closed as completed by t-affeldt** 2020-08-19 12:08 UTC
